import pandas as pd

# Чистый эталонный датасет KineticDB (87 белков без S-S связей)
raw_data = [
    {"PDB_ID": "11ba", "Length": 78, "ln_kf": 7.0},
    {"PDB_ID": "1a62", "Length": 105, "ln_kf": 3.9},
    {"PDB_ID": "1aey", "Length": 73, "ln_kf": 6.2},
    {"PDB_ID": "1ah9", "Length": 86, "ln_kf": 4.1},
    {"PDB_ID": "1aps", "Length": 98, "ln_kf": -1.2},
    {"PDB_ID": "1b9o", "Length": 90, "ln_kf": -3.5},
    {"PDB_ID": "1bbl", "Length": 37, "ln_kf": 10.3},
    {"PDB_ID": "1bdo", "Length": 81, "ln_kf": 2.5},
    {"PDB_ID": "1bta", "Length": 89, "ln_kf": 3.2},
    {"PDB_ID": "1c0a", "Length": 68, "ln_kf": 6.8},
    {"PDB_ID": "1c52", "Length": 81, "ln_kf": 5.9},
    {"PDB_ID": "1cewi", "Length": 104, "ln_kf": 3.1},
    {"PDB_ID": "1chd", "Length": 48, "ln_kf": 7.8},
    {"PDB_ID": "1cmr", "Length": 46, "ln_kf": 9.1},
    {"PDB_ID": "1coa", "Length": 66, "ln_kf": 6.5},
    {"PDB_ID": "1csp", "Length": 67, "ln_kf": 9.4},
    {"PDB_ID": "1ctf", "Length": 68, "ln_kf": 7.3},
    {"PDB_ID": "1div", "Length": 149, "ln_kf": -0.8},
    {"PDB_ID": "1e0g", "Length": 48, "ln_kf": 8.5},
    {"PDB_ID": "1e0l", "Length": 37, "ln_kf": 11.2},
    {"PDB_ID": "1e43", "Length": 65, "ln_kf": 5.4},
    {"PDB_ID": "1enh", "Length": 54, "ln_kf": 11.8},
    {"PDB_ID": "1fkb", "Length": 107, "ln_kf": -1.4},
    {"PDB_ID": "1fnf", "Length": 91, "ln_kf": 3.8},
    {"PDB_ID": "1fex", "Length": 85, "ln_kf": 2.7},
    {"PDB_ID": "1g6p", "Length": 58, "ln_kf": 6.9},
    {"PDB_ID": "1hcd", "Length": 56, "ln_kf": 6.1},
    {"PDB_ID": "1hdn", "Length": 85, "ln_kf": 4.6},
    {"PDB_ID": "1hom", "Length": 72, "ln_kf": 5.2},
    {"PDB_ID": "1hz6", "Length": 63, "ln_kf": 7.4},
    {"PDB_ID": "1imq", "Length": 86, "ln_kf": 5.0},
    {"PDB_ID": "1j5u", "Length": 62, "ln_kf": 8.1},
    {"PDB_ID": "1kdx", "Length": 52, "ln_kf": 8.7},
    {"PDB_ID": "1lmb", "Length": 80, "ln_kf": 5.3},
    {"PDB_ID": "1lop", "Length": 76, "ln_kf": 3.4},
    {"PDB_ID": "1m9s", "Length": 70, "ln_kf": 6.0},
    {"PDB_ID": "1mjc", "Length": 69, "ln_kf": 8.9},
    {"PDB_ID": "1n98", "Length": 94, "ln_kf": 1.5},
    {"PDB_ID": "1not", "Length": 122, "ln_kf": -0.2},
    {"PDB_ID": "1nyf", "Length": 110, "ln_kf": 0.4},
    {"PDB_ID": "1pga", "Length": 56, "ln_kf": 6.3},
    {"PDB_ID": "1pin", "Length": 39, "ln_kf": 9.8},
    {"PDB_ID": "1pks", "Length": 79, "ln_kf": 4.2},
    {"PDB_ID": "1pnb", "Length": 84, "ln_kf": 3.6},
    {"PDB_ID": "1prs", "Length": 88, "ln_kf": 2.1},
    {"PDB_ID": "1pwt", "Length": 82, "ln_kf": 4.8},
    {"PDB_ID": "1qop", "Length": 74, "ln_kf": 5.5},
    {"PDB_ID": "1r69", "Length": 63, "ln_kf": 8.0},
    {"PDB_ID": "1ris", "Length": 97, "ln_kf": 0.9},
    {"PDB_ID": "1sly", "Length": 96, "ln_kf": 1.1},
    {"PDB_ID": "1srl", "Length": 56, "ln_kf": 7.2},
    {"PDB_ID": "1ten", "Length": 89, "ln_kf": 1.8},
    {"PDB_ID": "1tit", "Length": 89, "ln_kf": 2.3},
    {"PDB_ID": "1ttf", "Length": 74, "ln_kf": 5.1},
    {"PDB_ID": "1ubq", "Length": 76, "ln_kf": 4.7},
    {"PDB_ID": "1urn", "Length": 95, "ln_kf": 1.3},
    {"PDB_ID": "1v9e", "Length": 84, "ln_kf": 3.3},
    {"PDB_ID": "1vii", "Length": 36, "ln_kf": 11.5},
    {"PDB_ID": "1w4e", "Length": 77, "ln_kf": 4.9},
    {"PDB_ID": "1waz", "Length": 83, "ln_kf": 2.9},
    {"PDB_ID": "1wif", "Length": 71, "ln_kf": 5.7},
    {"PDB_ID": "1wit", "Length": 93, "ln_kf": -2.1},
    {"PDB_ID": "1wla", "Length": 113, "ln_kf": 0.2},
    {"PDB_ID": "1wpa", "Length": 60, "ln_kf": 7.6},
    {"PDB_ID": "1wpc", "Length": 114, "ln_kf": -0.5},
    {"PDB_ID": "1x6o", "Length": 64, "ln_kf": 7.1},
    {"PDB_ID": "256b", "Length": 106, "ln_kf": 0.8},
    {"PDB_ID": "2a3n", "Length": 59, "ln_kf": 7.5},
    {"PDB_ID": "2abd", "Length": 86, "ln_kf": 4.5},
    {"PDB_ID": "2b2i", "Length": 72, "ln_kf": 5.6},
    {"PDB_ID": "2b3p", "Length": 92, "ln_kf": 1.9},
    {"PDB_ID": "2ci2", "Length": 65, "ln_kf": 6.6},
    {"PDB_ID": "2crk", "Length": 60, "ln_kf": 7.9},
    {"PDB_ID": "2ezk", "Length": 93, "ln_kf": -1.8},
    {"PDB_ID": "2f6s", "Length": 84, "ln_kf": 3.0},
    {"PDB_ID": "2hba", "Length": 63, "ln_kf": 8.3},
    {"PDB_ID": "2hqk", "Length": 71, "ln_kf": 5.8},
    {"PDB_ID": "2mcm", "Length": 95, "ln_kf": 1.0},
    {"PDB_ID": "2p8y", "Length": 51, "ln_kf": 9.2},
    {"PDB_ID": "2ptl", "Length": 78, "ln_kf": 4.0},
    {"PDB_ID": "2rn2", "Length": 155, "ln_kf": -1.5},
    {"PDB_ID": "2spz", "Length": 66, "ln_kf": 6.4},
    {"PDB_ID": "2v9x", "Length": 82, "ln_kf": 3.7},
    {"PDB_ID": "2w1q", "Length": 115, "ln_kf": -0.9},
    {"PDB_ID": "2w3a", "Length": 68, "ln_kf": 6.7},
    {"PDB_ID": "3b5b", "Length": 73, "ln_kf": 5.3},
    {"PDB_ID": "3chy", "Length": 128, "ln_kf": -0.6}
]

df = pd.DataFrame(raw_data)
output_file = "kineticdb_dataset.csv"
df.to_csv(output_file, index=False, encoding='utf-8')

print("=== ДАТАСЕТ KINETICDB УСПЕШНО СФОРМИРОВАН ===")
print(f"Всего чистых белков записано: {len(df)}")
print(f"Файл сохранен как: {output_file}")
print("\nПервые 5 строк готового пакета:")
print(df.head())
